### ISSUE TITLE
Implement onboarding flow

### ISSUE THREAD

**Issue by ozzmotic** [project-spectra/test-app#1]
Using current mockups as a guide, implement prototyped onboarding. 

Sub-tasks:

1. Generic card-view component that takes a list of components to display as cards.
	1. Should be bidirectional so that the user can move forward/backward.
	2. There's likely to be a (small) set of phrasing for prev/next buttons, so we could make these buttons components that emit events to the card-view component.

2. Onboarding cards:
	1. Ask for user's name
	2. Vocal health
	3. Select goal

**Comment by Transfusion** [comment]
Finished the onboarding cards with commit 01e9342dbc56234c2519dacb41ec712e782b6b94 in branch `onboarding-flow`

**Comment by Transfusion** [comment]
Test comment on an issue - let's see if this shows up in the Discord channel!

**Comment by ozzmotic** [comment]
Need to add a Disclaimer screen to this:

![Disclaimer Acknowledgment](https://user-images.githubusercontent.com/4603869/62732409-3e4d7a80-b9f2-11e9-815f-713323d0ff47.png)
