### ISSUE TITLE
Create a reusable tone/note synthesizer

### ISSUE THREAD

**Issue by Transfusion** [project-spectra/test-app#22]
Currently we resort to generating a pure sine wave in the `Set A Goal` screen and the `Hold That Note` warmup exercise. The two main problems are the abrupt starting and stopping of the wave causing loud clicks in the audio, and the speakers on certain devices being unable to reproduce certain frequencies accurately thus causing notes one octave apart to be practically indistinguishable.

A piano or musical instrument sample would work.

**Comment by plastichotsprings** [comment]
Fixed in #28 !
